### ISSUE TITLE
obtener MobileService y FixedTelephony

### ISSUE THREAD

**Issue by m4gen** [suitetecsa/sdk-kotlin#14]
MobileService y FixedTelephony está funcional? 

cuando ejecuto:
```java 
((User) response.getUser())
        .getServices()
        .getMobileServices()
        .forEach(mobileService ->{
          
System.out.println("result: " + mobileService);
});
```
la consola imprime: `result: [ ]` 

no pasa así con `MailService` y `NavService`, solo con `MobileService` y `FixedTelephony`

**Comment by lesclaz** [comment]
Le estás enviando bien todos los datos?

**Comment by m4gen** [comment]
lo estoy haciendo igual que con NavServices 
```java
     if (loginResponse.getResult().equals("ok")) {
                    // @loginResponse obtiene la info
                    User user = (User) loginResponse.getUser();

    List<MobileService> mobileServices = user.getServices().getMobileServices();
                for (int i = 0; i < mobileServices.size(); i++) {
                    saveMobileService(mobileServices.get(i));
                }
}
 private void saveMobileService(MobileService service) {
        String saldo = service.getProfile().getCurrency();
        getActivity().runOnUiThread(() -> Log.i("Movil", saldo));
    }
```

el log para getCurrency no devuelve nada, y estuve interceptando los datos antes de llegar ahi, si mal no recuerdo era que getMobileService(); devolvia  `[]`

**Comment by lesclaz** [comment]
La cosa está en que la respuesta de login no incluye los servicios móviles. En cuanto a FixedTelephony, el poseedor de la cuenta debe de tener un teléfono fijo a su nombre para que la api devuelva algo.

**Comment by m4gen** [comment]
ah vale, entiendo. gracias.
